services:
  api:
    build: ./API
    ports:
      - "3000:3000"
    environment:
      PGUSER: admin
      PGPASSWORD: secret
      PGHOST: postgres
      PGDATABASE: mydb
      PGPORT: 5432
    depends_on:
      - postgres

  dotnet-api:
    build: ./DotnetDockerApi  # Ajusta según la ruta donde tengas el Dockerfile .NET
    ports:
      - "5000:8080"  # .NET escucha en el puerto 80 por default
    environment:
      PGUSER: admin
      PGPASSWORD: secret
      PGHOST: postgres
      PGDATABASE: mydb
      PGPORT: 5432
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
